"""create_media_table

Revision ID: 902306be9f36
Revises: 2df1fd5c01b9
Create Date: 2024-06-24 23:37:16.283165

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '902306be9f36'
down_revision = '2df1fd5c01b9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('multimedia',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('external_id', sa.String(), nullable=True),
                    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
                    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
                    sa.Column('title', sa.String(), nullable=True),
                    sa.Column('tags', sa.String(), nullable=True),
                    sa.Column('lyric', sa.String(), nullable=True),
                    sa.Column('image_url', sa.String(), nullable=True),
                    sa.Column('audio_url', sa.String(), nullable=True),
                    sa.Column('video_url', sa.String(), nullable=True),
                    sa.Column('duration', sa.Float, nullable=True),
                    sa.Column('source', sa.String(), nullable=True),
                    sa.Column('model_name', sa.String(), nullable=True),
                    sa.Column('model_version', sa.String(), nullable=True),
                    sa.Column('has_vocal', sa.String(), nullable=True),
                    sa.Column('music_type', sa.String(), nullable=True),
                    sa.Column('instrumental_type', sa.String(), nullable=True),
                    sa.PrimaryKeyConstraint('id', name=op.f('pk_multimedia'))
                    )
    op.create_index(op.f('ix_multimedia_created_at'), 'multimedia', ['created_at'], unique=False)
    op.create_index(op.f('ix_multimedia_updated_at'), 'multimedia', ['updated_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_multimedia_updated_at'), table_name='multimedia')
    op.drop_index(op.f('ix_multimedia_created_at'), table_name='multimedia')
    op.drop_table('multimedia')
    # ### end Alembic commands ###
