version: '3.8'

services:
  tautobet-app:
    image: $BASE_IMAGE_NAME
    container_name: $APP_CONTAINER_NAME
    working_dir: /app
    command: bash -c 'while !</dev/tcp/tautobet-db/5432; do sleep 1; done; uvicorn tautobet.app:app --host 0.0.0.0 --port $APP_PORT'
    volumes:
      - ../../:/app
    expose:
      - $APP_PORT

#    labels: # new
#      - "traefik.enable=true"
#      - "traefik.docker.network=proxy"
#      - "traefik.http.routers.${APP_CONTAINER_NAME}.rule=Host(`${APP_HOST}`)"
#      - "traefik.http.routers.${APP_CONTAINER_NAME}.entrypoints=websecure"
#      - "traefik.http.routers.${APP_CONTAINER_NAME}.tls=true"
#      - "traefik.http.routers.${APP_CONTAINER_NAME}.tls.certresolver=letsencrypt"

    networks:
      - proxy
      - default

  tautobet-db:
    image: postgres:15-alpine
    shm_size: '1gb'
    restart: unless-stopped

    ports:
      - $PUBLIC_DB_PORT:5432

    environment:
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASS
      POSTGRES_DB: $DB_NAME

    volumes:
      - ./.container-volume:/var/lib/postgresql/data  # persist postgres data ref. https://stackoverflow.com/a/41650891/248616

    container_name: $DB_CONTAINER_NAME

    networks:
      - default

networks:
  proxy:
    external: true

volumes:
  cache:
    driver: local
